# Generated by Django 5.2.17 on 2026-09-05 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('legal_name', models.CharField(max_length=255, unique=True, verbose_name='Legal name')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('accounting_currency', models.ForeignKey(help_text='Immutable after creation; a new currency requires a new LegalEntity.', on_delete=django.db.models.deletion.PROTECT, related_name='legal_entities', to='currencies.currency', verbose_name='Accounting currency')),
            ],
            options={
                'verbose_name': 'Legal entity',
                'verbose_name_plural': 'Legal entities',
                'db_table': 'merchants_legalentity',
                'ordering': ('legal_name',),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Stable public channel identifier.', max_length=100, unique=True, verbose_name='Slug')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='merchants.legalentity', verbose_name='Legal entity')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'db_table': 'merchants_store',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='StoreMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 sales geography of the market.', max_length=2, verbose_name='Country code')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('payment_currencies', models.ManyToManyField(help_text='Currencies the buyer may pay with in this market.', related_name='store_markets', to='currencies.currency', verbose_name='Enabled payment currencies')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='merchants.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Store market',
                'verbose_name_plural': 'Store markets',
                'db_table': 'merchants_storemarket',
                'ordering': ('country_code',),
            },
        ),
        migrations.AddConstraint(
            model_name='legalentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='legalentity_single_active'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('legal_entity', 'name'), name='store_entity_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='storemarket',
            constraint=models.CheckConstraint(condition=models.Q(('country_code__regex', '^[A-Z]{2}$')), name='storemarket_country_iso_alpha2'),
        ),
        migrations.AddConstraint(
            model_name='storemarket',
            constraint=models.UniqueConstraint(fields=('store', 'country_code'), name='storemarket_store_country_uniq'),
        ),
        migrations.AddConstraint(
            model_name='storemarket',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('store', 'is_active'), name='storemarket_active_per_store'),
        ),
    ]
