# Generated by Django 5.2.17 on 2026-09-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_external_id_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('nonce', models.CharField(max_length=128, unique=True, verbose_name='Nonce')),
                ('webhook_timestamp', models.BigIntegerField(verbose_name='Webhook timestamp')),
            ],
            options={
                'verbose_name': 'Webhook nonce',
                'verbose_name_plural': 'Webhook nonces',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['webhook_timestamp'], name='webhook_nonce_ts_idx')],
            },
        ),
    ]
